function dffV_warpped = warpToAllen(filename)
%% Created by Hemanth Mohan, largely modified by Hermione Xu.
%  This function is called within dffVSlider_withSignal_2.m only when the
%  Load Warpped Data button was clicked. 
load(filename);
% Check if dorsalMap exists
filenameSplit = split(filename,'\');
dorsalMapPath = [filenameSplit{1} filesep filenameSplit{2} filesep ...
    filenameSplit{4} filesep filenameSplit{5} filesep 'HX3_dorsalMap.mat']; % Filename needs more work TODO
if isfile(dorsalMapPath)
    load(dorsalMapPath);
else
    fprintf('Dorsal Map needs to be generated by calling FitAllenCCF3toFoV_Spont_1.m');
    run('D:\Scripts\allen_map\FitAllenCCF3toFoV_Spont_1.m')
end

tform = dorsalMaps.tform;
dmMap = dorsalMaps.edgeOutlineSplit;
dffV_warpped= imwarp(dffV,tform,'OutputView',imref2d(size(dorsalMaps.dorsalMapScaled))).*dorsalMaps.maskScaled;

% save file 
saveMap = input('Do you want to save the wrapped dffV: ');
if saveMap
    savePathTemp = split(filename,'.');
    savePath = [savePathTemp{1} '_warpped.mat'];
    disp('Saving the Signal File')
    save(savePath,'dffV_warpped','-v7.3');
    disp('File Saved')
end